name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: "${{ github.repository_owner == 'eBay' && github.event_name == 'push' }}"
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: BASE_URL=/opensource-website/ npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
